In [4]:
import numpy as np
R = np.random.randint(1,257, size=(5, 5))
G = np.random.randint(1,257, size=(5, 5))
B = np.random.randint(1,257, size=(5, 5))
print("R=",R)
print("G=",G)
print("B=",B)
I = 0.6*R - 0.28*G - 0.32*B
Q = 0.21*R - 0.52*G - 0.31*B
print("I=",I)
print("Q=",Q)

#R=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
#G=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
#B=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
#R[1][1]
#for i in range (0,5)   
 #for j in range (0,5)
    #I[i][j]=.6*R[i],[j]-.20*G[i][j]-.32B[i][j]
#r=np.array([[R,R],[R,R]])    //data concatenation(10X10) array


R= [[155  86  72  57  83]
 [ 92 237 132  59 118]
 [231 118 118  33 157]
 [ 67  25  41 239 185]
 [229 153 195  78 156]]
G= [[ 30 180  93  64  21]
 [102  82 200 248 176]
 [208  34 150  24  95]
 [ 17 251 191 170  19]
 [230 221  21  53 113]]
B= [[204  12  35 161 114]
 [ 26 253 252  43  79]
 [214  38  68 192 240]
 [253 183 236  29 125]
 [236 196 166  54 155]]
I= [[  19.32   -2.64    5.96  -35.24    7.44]
 [  18.32   38.28  -57.44  -47.8    -3.76]
 [  11.88   49.12    7.04  -48.36   -9.2 ]
 [ -45.52 -113.84 -104.4    86.52   65.68]
 [  -2.52  -32.8    58.     14.68   12.36]]
Q= [[ -46.29  -79.26  -44.09  -71.22  -28.83]
 [ -41.78  -71.3  -154.4  -129.9   -91.23]
 [-125.99   -4.68  -74.3   -65.07  -90.83]
 [ -73.2  -182.   -163.87  -47.2    -9.78]
 [-144.67 -143.55  -21.43  -27.92  -74.05]]
